import autechreArtist from '../../assets/vinyl-vault/autechre-artist-full.jpg';
import boardsArtistModal from '../../assets/vinyl-vault/boards-of-canada-modal-artist.png';
import boardsArtist from '../../assets/vinyl-vault/boards-of-canada-artist.png';
import comeToDaddyCover from '../../assets/vinyl-vault/come-to-daddy-cover.png';
import djShadowArtist from '../../assets/vinyl-vault/dj-shadow-artist.png';
import drukqsAnniversaryVinylDisplay from '../../assets/vinyl-vault/drukqs-anniversary-vinyl-display.png';
import drukqsCover from '../../assets/vinyl-vault/drukqs-cover.png';
import geogaddiCover from '../../assets/vinyl-vault/geogaddi-cover.png';
import heroBackground from '../../assets/vinyl-vault/hero-background.png';
import musicHasTheRightCover from '../../assets/vinyl-vault/music-has-the-right-cover.png';
import placeholderCover from '../../assets/vinyl-vault/album-placeholder.svg';
import selectedAmbientCover from '../../assets/vinyl-vault/selected-ambient-cover.png';
import tomorrowsHarvestCover from '../../assets/vinyl-vault/tomorrows-harvest-cover.png';
import aphexArtist from '../../assets/vinyl-vault/aphex-twin-artist.png';
import type { ArtistDetails, HomePageData } from './home.types';

export const homePageMockData: HomePageData = {
  heroPromotions: [
    {
      id: 'drukqs-anniversary',
      eyebrowMarks: ['aphex', 'warp'],
      title: 'Drukqs - 25th Anniversary Reissue',
      releaseLine: 'Out 30 October 2026',
      description:
        "Aphex Twin's landmark 2001 album returns to vinyl in a special 4xLP anniversary edition",
      ctaLabel: 'Go to album',
      albumSlug: 'drukqs',
      backgroundSrc: heroBackground,
      artworkSrc: drukqsAnniversaryVinylDisplay,
      artworkAlt: 'Drukqs anniversary edition cover art with vinyl record',
    },
  ],
  albumsOfTheWeek: [
    {
      id: 'drukqs',
      slug: 'drukqs',
      artistSlug: 'aphex-twin',
      artist: 'Aphex Twin',
      title: 'Drukqs',
      coverSrc: drukqsCover,
      coverAlt: 'Aphex Twin Drukqs album cover',
    },
    {
      id: 'come-to-daddy',
      slug: 'come-to-daddy',
      artistSlug: 'aphex-twin',
      artist: 'Aphex Twin',
      title: 'Come to Daddy',
      coverSrc: comeToDaddyCover,
      coverAlt: 'Aphex Twin Come to Daddy album cover',
    },
    {
      id: 'selected-ambient-works-85-92',
      slug: 'selected-ambient-works-85-92',
      artistSlug: 'aphex-twin',
      artist: 'Aphex Twin',
      title: 'Selected Ambient Works 85-92',
      coverSrc: selectedAmbientCover,
      coverAlt: 'Aphex Twin Selected Ambient Works 85-92 album cover',
    },
    {
      id: 'tomorrows-harvest',
      slug: 'tomorrows-harvest',
      artistSlug: 'boards-of-canada',
      artist: 'Boards of Canada',
      title: "Tomorrow's Harvest",
      coverSrc: tomorrowsHarvestCover,
      coverAlt: "Boards of Canada Tomorrow's Harvest album cover",
    },
    {
      id: 'music-has-the-right-to-children',
      slug: 'music-has-the-right-to-children',
      artistSlug: 'boards-of-canada',
      artist: 'Boards of Canada',
      title: 'Music Has the Right to Children',
      coverSrc: musicHasTheRightCover,
      coverAlt: 'Boards of Canada Music Has the Right to Children album cover',
    },
    {
      id: 'geogaddi',
      slug: 'geogaddi',
      artistSlug: 'boards-of-canada',
      artist: 'Boards of Canada',
      title: 'Geogaddi',
      coverSrc: geogaddiCover,
      coverAlt: 'Boards of Canada Geogaddi album cover',
    },
  ],
  featuredArtists: [
    {
      id: 'aphex-twin',
      slug: 'aphex-twin',
      name: 'Aphex Twin',
      imageSrc: aphexArtist,
      imageAlt: 'Portrait of Aphex Twin',
      width: 'medium',
      hasDetails: true,
    },
    {
      id: 'boards-of-canada',
      slug: 'boards-of-canada',
      name: 'Boards of Canada',
      imageSrc: boardsArtist,
      imageAlt: 'Boards of Canada artist photo',
      width: 'wide',
      hasDetails: true,
    },
    {
      id: 'dj-shadow',
      slug: 'dj-shadow',
      name: 'DJ Shadow',
      imageSrc: djShadowArtist,
      imageAlt: 'DJ Shadow artist photo',
      width: 'narrow',
      hasDetails: true,
    },
    {
      id: 'autechre',
      slug: 'autechre',
      name: 'Autechre',
      imageSrc: autechreArtist,
      imageAlt: 'Autechre artist photo',
      width: 'narrow',
      hasDetails: true,
    },
  ],
  recommendedAlbums: [
    {
      id: 'incunabula',
      slug: 'incunabula',
      artistSlug: 'autechre',
      artist: 'Autechre',
      title: 'Incunabula',
      coverSrc: placeholderCover,
      coverAlt: 'Placeholder cover for Autechre Incunabula',
      isPlaceholder: true,
    },
    {
      id: 'tri-repetae',
      slug: 'tri-repetae',
      artistSlug: 'autechre',
      artist: 'Autechre',
      title: 'Tri Repetae',
      coverSrc: placeholderCover,
      coverAlt: 'Placeholder cover for Autechre Tri Repetae',
      isPlaceholder: true,
    },
    {
      id: 'amber',
      slug: 'amber',
      artistSlug: 'autechre',
      artist: 'Autechre',
      title: 'Amber',
      coverSrc: placeholderCover,
      coverAlt: 'Placeholder cover for Autechre Amber',
      isPlaceholder: true,
    },
    {
      id: 'endtroducing',
      slug: 'endtroducing',
      artistSlug: 'dj-shadow',
      artist: 'DJ Shadow',
      title: 'Endtroducing.....',
      coverSrc: placeholderCover,
      coverAlt: 'Placeholder cover for DJ Shadow Endtroducing',
      isPlaceholder: true,
    },
    {
      id: 'the-private-press',
      slug: 'the-private-press',
      artistSlug: 'dj-shadow',
      artist: 'DJ Shadow',
      title: 'The Private Press',
      coverSrc: placeholderCover,
      coverAlt: 'Placeholder cover for DJ Shadow The Private Press',
      isPlaceholder: true,
    },
    {
      id: 'the-less-you-know-the-better',
      slug: 'the-less-you-know-the-better',
      artistSlug: 'dj-shadow',
      artist: 'DJ Shadow',
      title: 'The Less You Know, the Better',
      coverSrc: placeholderCover,
      coverAlt: 'Placeholder cover for DJ Shadow The Less You Know, the Better',
      isPlaceholder: true,
    },
  ],
};

export const artistDetailsMockData: ArtistDetails[] = [
  {
    id: 'aphex-twin',
    slug: 'aphex-twin',
    name: 'Aphex Twin',
    imageSrc: aphexArtist,
    imageAlt: 'Portrait of Aphex Twin',
    biography:
      'Aphex Twin is the main recording alias of Richard D. James, a British electronic musician known for reshaping ambient techno, acid, IDM and experimental electronic music. His catalog moves between delicate melodic sketches, distorted drum programming and disorienting sound design, making records like Selected Ambient Works 85-92, Come to Daddy and Drukqs enduring reference points for electronic music collectors.',
    albums: [
      {
        id: 'drukqs',
        slug: 'drukqs',
        artistSlug: 'aphex-twin',
        artist: 'Aphex Twin',
        title: 'Drukqs',
        coverSrc: drukqsCover,
        coverAlt: 'Aphex Twin Drukqs album cover',
      },
      {
        id: 'come-to-daddy',
        slug: 'come-to-daddy',
        artistSlug: 'aphex-twin',
        artist: 'Aphex Twin',
        title: 'Come to Daddy',
        coverSrc: comeToDaddyCover,
        coverAlt: 'Aphex Twin Come to Daddy album cover',
      },
      {
        id: 'selected-ambient-works-85-92',
        slug: 'selected-ambient-works-85-92',
        artistSlug: 'aphex-twin',
        artist: 'Aphex Twin',
        title: 'Selected Ambient Works 85-92',
        coverSrc: selectedAmbientCover,
        coverAlt: 'Aphex Twin Selected Ambient Works 85-92 album cover',
      },
    ],
  },
  {
    id: 'boards-of-canada',
    slug: 'boards-of-canada',
    name: 'Boards of Canada',
    imageSrc: boardsArtistModal,
    imageAlt: 'Boards of Canada electronic music duo',
    biography:
      "Boards of Canada are a Scottish electronic duo formed by brothers Michael Sandison and Marcus Eoin. Their name was inspired by the National Film Board of Canada, whose old educational films helped shape the faded, dreamlike character of their music. Blending analogue synthesizers, worn tape textures, hip-hop-influenced rhythms and fragmented voices, the duo creates music that feels nostalgic, beautiful and quietly unsettling. Their landmark 1998 album Music Has the Right to Children established their unmistakable sound, followed by Geogaddi, The Campfire Headphase and the darker, cinematic Tomorrow's Harvest. After thirteen years without a studio album, Boards of Canada returned in 2026 with Inferno.",
    albums: [
      {
        id: 'inferno',
        slug: 'inferno',
        artistSlug: 'boards-of-canada',
        artist: 'Boards of Canada',
        title: 'Inferno',
        coverSrc: placeholderCover,
        coverAlt: 'Placeholder cover for Boards of Canada Inferno',
        isPlaceholder: true,
      },
      {
        id: 'tomorrows-harvest',
        slug: 'tomorrows-harvest',
        artistSlug: 'boards-of-canada',
        artist: 'Boards of Canada',
        title: "Tomorrow's Harvest",
        coverSrc: tomorrowsHarvestCover,
        coverAlt: "Boards of Canada Tomorrow's Harvest album cover",
      },
      {
        id: 'geogaddi',
        slug: 'geogaddi',
        artistSlug: 'boards-of-canada',
        artist: 'Boards of Canada',
        title: 'Geogaddi',
        coverSrc: geogaddiCover,
        coverAlt: 'Boards of Canada Geogaddi album cover',
      },
      {
        id: 'the-campfire-headphase',
        slug: 'the-campfire-headphase',
        artistSlug: 'boards-of-canada',
        artist: 'Boards of Canada',
        title: 'The Campfire Headphase',
        coverSrc: placeholderCover,
        coverAlt:
          'Placeholder cover for Boards of Canada The Campfire Headphase',
        isPlaceholder: true,
      },
      {
        id: 'music-has-the-right-to-children',
        slug: 'music-has-the-right-to-children',
        artistSlug: 'boards-of-canada',
        artist: 'Boards of Canada',
        title: 'Music Has the Right to Children',
        coverSrc: musicHasTheRightCover,
        coverAlt:
          'Boards of Canada Music Has the Right to Children album cover',
      },
    ],
  },
  {
    id: 'autechre',
    slug: 'autechre',
    name: 'Autechre',
    imageSrc: autechreArtist,
    imageAlt: 'Autechre artist portrait',
    biography:
      'Autechre are the Manchester electronic duo Rob Brown and Sean Booth. Their work is associated with Warp Records and a precise, exploratory approach to rhythm, texture and synthesis. Early albums such as Incunabula, Amber and Tri Repetae helped define a colder, more architectural side of 1990s electronic music while still keeping a strong sense of movement and atmosphere.',
    albums: [
      {
        id: 'incunabula',
        slug: 'incunabula',
        artistSlug: 'autechre',
        artist: 'Autechre',
        title: 'Incunabula',
        coverSrc: placeholderCover,
        coverAlt: 'Placeholder cover for Autechre Incunabula',
        isPlaceholder: true,
      },
      {
        id: 'tri-repetae',
        slug: 'tri-repetae',
        artistSlug: 'autechre',
        artist: 'Autechre',
        title: 'Tri Repetae',
        coverSrc: placeholderCover,
        coverAlt: 'Placeholder cover for Autechre Tri Repetae',
        isPlaceholder: true,
      },
      {
        id: 'amber',
        slug: 'amber',
        artistSlug: 'autechre',
        artist: 'Autechre',
        title: 'Amber',
        coverSrc: placeholderCover,
        coverAlt: 'Placeholder cover for Autechre Amber',
        isPlaceholder: true,
      },
    ],
  },
  {
    id: 'dj-shadow',
    slug: 'dj-shadow',
    name: 'DJ Shadow',
    imageSrc: djShadowArtist,
    imageAlt: 'DJ Shadow artist photo',
    biography:
      'DJ Shadow is an American producer and DJ whose sample-based records connect hip-hop, turntablism, funk, psych and cinematic electronic music. Endtroducing..... became a landmark for dense vinyl sampling and atmospheric beat construction, followed by later records that continued to push between crate-digging culture and widescreen production.',
    albums: [
      {
        id: 'endtroducing',
        slug: 'endtroducing',
        artistSlug: 'dj-shadow',
        artist: 'DJ Shadow',
        title: 'Endtroducing.....',
        coverSrc: placeholderCover,
        coverAlt: 'Placeholder cover for DJ Shadow Endtroducing',
        isPlaceholder: true,
      },
      {
        id: 'the-private-press',
        slug: 'the-private-press',
        artistSlug: 'dj-shadow',
        artist: 'DJ Shadow',
        title: 'The Private Press',
        coverSrc: placeholderCover,
        coverAlt: 'Placeholder cover for DJ Shadow The Private Press',
        isPlaceholder: true,
      },
      {
        id: 'the-less-you-know-the-better',
        slug: 'the-less-you-know-the-better',
        artistSlug: 'dj-shadow',
        artist: 'DJ Shadow',
        title: 'The Less You Know, the Better',
        coverSrc: placeholderCover,
        coverAlt:
          'Placeholder cover for DJ Shadow The Less You Know, the Better',
        isPlaceholder: true,
      },
    ],
  },
];
